---
title: "A comparison of single-cell trajectory inference methods: towards more accurate and robust tools"
bibliography: references.bib
csl: nature-biotechnology.csl
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage[table]{xcolor}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{tabu}
  - \usepackage[normalem]{ulem}
  - \usepackage{lscape}
  - \usepackage{pbox}
  - \usepackage[labelformat=empty]{caption}
  - \usepackage{hyperref}
  - \hypersetup{colorlinks=true}
  - \ExecuteBibliographyOptions{sorting=none,sortcites=true,autocite=superscript,autopunct=false}
  - \newcommand{\hideFromPandoc}[1]{#1}
  - \hideFromPandoc{\let\Begin\begin}
  - \hideFromPandoc{\let\End\end}
  - \hideFromPandoc{\newenvironment{myfigure}[1]{\begin{figure}[#1]}{\end{figure}}}
mainfont: Open Sans


---


<!--
Tips for working in this document:
Go to tools -> preferences and remove Use smart quotes
Enable automatic zotero syncing to bibtex
Make sure to pin the zotero bibtex references after first using them!
-->


```{r setup, include=FALSE}
source(paste0(dynalysis::get_dynalysis_folder(), "/analysis/paper/setup.R"))

# knitr options
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = paste0(rprojroot::find_rstudio_root_file(), "/analysis/paper/.scratch/")
)
```

```{r "supplementary", echo=FALSE, results='asis', warning=FALSE}
list2env(read_rds(derived_file("sfigs_stables.rds", "paper")), environment())
source(paste0(dynalysis::get_dynalysis_folder(), "/analysis/paper/sfigs_stables.R"))
```
