# get the base image, the rocker/verse has R, RStudio and pandoc
FROM rocker/verse:latest

# install rstan on top of this
FROM jrnold/rstan

# set maximum dlls to 250
ENV R_MAX_NUM_DLLS 250

# set up github path, given by an argument in the docker build
ARG GITHUB_PAT
ENV GITHUB_PAT=$GITHUB_PAT
