FROM dynalysis_dependencies

# required
MAINTAINER Wouter Saelens <wouter.saelens@ugent.be>
MAINTAINER Robrecht Cannoodt <robrecht.cannoodt@ugent.be>

# update all dependencies of dynalysis, packages which are already installed will not be reinstalled
RUN . /etc/environment && R -e "devtools::install('dynalysis', dependencies=TRUE, upgrade_dependencies=TRUE)"

RUN . /etc/environment \
  && R -e "library(dynmethods);dynmethods::check_dependencies()"

# manuscript render
RUN . /etc/environment \
  && R -e "rmarkdown::render('dynalysis/analysis/paper/paper.Rmd')"
