FROM dynalysis_env

# update aptitude
RUN sudo apt-get update

# install many python requirements, all else will be installed in virtual environments
RUN sudo apt-get install python2.7-dev python3-dev python3-pip -y
RUN pip3 install virtualenv

# for pySCUBA
RUN sudo apt-get install python3-tk -y

RUN . /etc/environment \
  && sudo apt-get update \
  && sudo apt-get install subversion -y \
  && sudo apt-get install libudunits2-dev libgsl-dev libsdl1.2-dev libreadline-dev imagemagick libfftw3-dev libudunits2-dev librsvg2-dev -y

RUN python3 -m pip install numpy matplotlib pandas six jinja2 python-dateutil pytz pyparsing cycler tqdm python-igraph rpy2 Cython scipy statsmodels sklearn seaborn

# copy all local dynalysis files to docker
COPY . dynalysis

# build package
RUN . /etc/environment && R -e 'install.packages("devtools")'
RUN . /etc/environment && R -e 'setRepositories(ind = 1:2); devtools::install_github("Zouter/dynalysis", dependencies = T, upgrade = T)'
