execution_error_metrics <- as.list(error_reasons$name)

metric_ord <- tribble(
  ~experiment,     ~category,     ~metric,                  ~id,    ~name,                    ~geom,
  "method",      "overall",       "name",                   "name", "Name",                   "text(hjust = 0, width = 6, show_label = FALSE)",
  "method",      "overall",       "priors",                 "prio", "Priors required",        "text",
  "method",      "overall",       "wrapper_type",           "wrty", "Wrapper type",           "text",
  "method",      "overall",       "platform",               "ptfm", "Platform",               "text",
  "method",      "overall",       "topology_inference",     "topi", "Topology inference",     "text",
  "method",      "overall",       "most_complex",           "mcpx", "Max. traj. type",        "traj",
  "method",       "ttinfer",      "tt_cycle",               "ttcy", "Cycle",                  "traj",
  "method",       "ttinfer",      "tt_linear",              "ttli", "Linear",                 "traj",
  "method",       "ttinfer",      "tt_bifurcation",         "ttbi", "Bifurcation",            "traj",
  "method",       "ttinfer",      "tt_convergence",         "ttco", "Convergence",            "traj",
  "method",       "ttinfer",      "tt_multifurcation",      "ttmu", "Multifurcation",         "traj",
  "method",       "ttinfer",      "tt_tree",                "tttr", "Tree",                   "traj",
  "method",       "ttinfer",      "tt_acyclic_graph",       "ttac", "Acyclic",                "traj",
  "method",       "ttinfer",      "tt_graph",               "ttgr", "Connected",              "traj",
  "method",       "ttinfer",      "tt_disconnected_graph",  "ttdi", "Disconnected",           "traj",
  "summary",      "overall",      "overall",                "over", "Overall",                "bar",
  "summary",      "overall",      "benchmark",              "oveb", "Benchmark",              "bar",
  "summary",      "overall",      "stability",              "ovet", "Stability",              "bar",
  "summary",      "overall",      "scalability",            "oves", "Scalability",            "bar",
  "summary",      "overall",      "qc",                     "oveq", "QC",                     "bar",
  "summary",      "overall",      "control_label",          "conl", "",                       "text(overlay = TRUE)",
  "benchmark",    "metric",       "norm_correlation",       "gcor", "Ordering",               "circle",
  "benchmark",    "metric",       "norm_him",               "him_", "Topology",               "circle",
  "benchmark",    "metric",       "norm_featureimp_wcor",   "fcor", "Features",               "circle",
  "benchmark",    "metric",       "norm_F1_branches",       "f1br", "Clustering",             "circle",
  "benchmark",    "sources",      "real/gold",              "rego", "Gold",                   "circle",
  "benchmark",    "sources",      "real/silver",            "resi", "Silver",                 "circle",
  "benchmark",    "sources",      "synthetic/dyngen",       "dyng", "dyngen",                 "circle",
  "benchmark",    "sources",      "synthetic/dyntoy",       "dynt", "dyntoy",                 "circle",
  "benchmark",    "sources",      "synthetic/prosstt",      "pros", "PROSSTT",                "circle",
  "benchmark",    "sources",      "synthetic/splatter",     "spla", "Splatter",               "circle",
  "benchmark",    "trajtypes",    "cycle",                  "circ", "Cycle",                  "circle",
  "benchmark",    "trajtypes",    "linear",                 "line", "Linear",                 "circle",
  "benchmark",    "trajtypes",    "bifurcation",            "bifu", "Bifurcation",            "circle",
  "benchmark",    "trajtypes",    "convergence",            "conv", "Convergence",            "circle",
  "benchmark",    "trajtypes",    "multifurcation",         "mult", "Multifurcation",         "circle",
  "benchmark",    "trajtypes",    "tree",                   "tree", "Tree",                   "circle",
  "benchmark",    "trajtypes",    "acyclic_graph",          "acyc", "Acyclic",                "circle",
  "benchmark",    "trajtypes",    "graph",                  "conn", "Connected",              "circle",
  "benchmark",    "trajtypes",    "disconnected_graph",     "disc", "Disconnected",           "circle",
  "benchmark",    "execution",    "pct_errored",            "errp", "% Errored",              "text(format = 'percentage')",
  "benchmark",    "execution",    execution_error_metrics,  "errr", "Reason",                 "pie",
  "benchmark",    "stability",    "var_overall",            "vove", "Overall",                "circle",
  "benchmark",    "stability",    "var_correlation",        "vcor", "Ordering",               "circle",
  "benchmark",    "stability",    "var_him",                "vhim", "Topology",               "circle",
  "benchmark",    "stability",    "var_featureimp_wcor",    "vfco", "Features",               "circle",
  "benchmark",    "stability",    "var_F1_branches",        "vf1b", "Clustering",             "circle",
  "scalability",  "10k features", "1k cells",               "sca1", "1k cells",               "textbox",
  "scalability",  "10k features", "10k cells",              "sca2", "10k cells",              "textbox",
  "scalability",  "10k features", "100k cells",             "sca3", "100k cells",             "textbox",
  "scalability",  "10k cells",    "1k features",            "sca1", "1k features",            "textbox",
  "scalability",  "10k cells",    "10k features",           "sca2", "10k features",           "textbox",
  "scalability",  "10k cells",    "100k features",          "sca3", "100k features",          "textbox",
  "qc",           "application",  "user_friendly",          "quse", "User friendly",          "circle",
  "qc",           "application",  "developer_friendly",     "qdev", "Developer friendly",     "circle",
# "qc",           "application",  "future_proof",           "qfut", "Future proof",           "circle",
  "qc",           "category",     "availability",           "qava", "Availability",           "circle",
  "qc",           "category",     "behaviour",              "qbeh", "Behaviour",              "circle",
  "qc",           "category",     "code_assurance",         "qass", "Code assurance",         "circle",
  "qc",           "category",     "code_quality",           "qqua", "Code quality",           "circle",
  "qc",           "category",     "documentation",          "qdoc", "Documentation",          "circle",
  "qc",           "category",     "paper",                  "qpap", "Paper",                  "circle"
)
