# please don't use the character " within the tribble below
# or other parts of the code will flip out.
# use the character ' instead

column_info <- tribble( # tribble_start
  ~group,                   ~id,                                            ~name,                      ~geom,     ~palette,         ~options,
  "method_characteristic",  "method_name",                                  "",                         "text",    NA,               list(hjust = 0, width = 6),
  "method_characteristic",  "method_priors_required_str",                   "Priors required",          "text",    NA,               list(width = 2),
  "method_characteristic",  "method_wrapper_type",                          "Wrapper type",             "text",    NA,               list(width = 2),
  "method_characteristic",  "method_platform",                              "Platform",                 "text",    NA,               list(width = 2),
  "method_characteristic",  "method_topology_inference",                    "Topology inference",       "text",    NA,               list(width = 2),
  "method_characteristic",  "method_most_complex_trajectory_type",          "Most complex traj. type",  "traj",    NA,               list(width = 2),
  "inferrable_trajtype",    "itt_cycle",                                    "Cycle",                    "traj",    NA,               list(width = 2),
  "inferrable_trajtype",    "itt_linear",                                   "Linear",                   "traj",    NA,               list(width = 2),
  "inferrable_trajtype",    "itt_bifurcation",                              "Bifurcation",              "traj",    NA,               list(width = 2),
  "inferrable_trajtype",    "itt_convergence",                              "Convergence",              "traj",    NA,               list(width = 2),
  "inferrable_trajtype",    "itt_multifurcation",                           "Multifurcation",           "traj",    NA,               list(width = 2),
  "inferrable_trajtype",    "itt_tree",                                     "Tree",                     "traj",    NA,               list(width = 2),
  "inferrable_trajtype",    "itt_acyclic_graph",                            "Acyclic",                  "traj",    NA,               list(width = 2),
  "inferrable_trajtype",    "itt_graph",                                    "Connected",                "traj",    NA,               list(width = 2),
  "inferrable_trajtype",    "itt_disconnected_graph",                       "Disconnected",             "traj",    NA,               list(width = 2),
  "score_overall",          "summary_overall_overall",                      "Overall",                  "bar",     "overall",        list(width = 4, legend = FALSE),
  "score_overall",          "benchmark_overall_overall",                    "Benchmark",                "bar",     "benchmark",      list(width = 4, legend = FALSE),
  "score_overall",          "scaling_pred_timescore_overall",               "Scalability",              "bar",     "scaling",        list(width = 4, legend = FALSE),
  "score_overall",          "stability_overall_overall",                    "Stability",                "bar",     "stability",      list(width = 4, legend = FALSE),
  "score_overall",          "qc_overall_overall",                           "Quality Control",          "bar",     "qc",             list(width = 4, legend = FALSE),
  "score_overall",          "control_label",                                "",                         "text",    NA,               list(overlay = TRUE),
  "benchmark_metric",       "benchmark_overall_norm_correlation",           "Ordering",                 "circle",  "benchmark",      lst(),
  "benchmark_metric",       "benchmark_overall_norm_him",                   "Topology",                 "circle",  "benchmark",      lst(),
  "benchmark_metric",       "benchmark_overall_norm_featureimp_wcor",       "Features",                 "circle",  "benchmark",      lst(),
  "benchmark_metric",       "benchmark_overall_norm_F1_branches",           "Clustering",               "circle",  "benchmark",      lst(),
  "benchmark_source",       "benchmark_source_real_gold",                   "Gold",                     "circle",  "benchmark",      lst(),
  "benchmark_source",       "benchmark_source_real_silver",                 "Silver",                   "circle",  "benchmark",      lst(),
  "benchmark_source",       "benchmark_source_synthetic_dyngen",            "dyngen",                   "circle",  "benchmark",      lst(),
  "benchmark_source",       "benchmark_source_synthetic_dyntoy",            "dyntoy",                   "circle",  "benchmark",      lst(),
  "benchmark_source",       "benchmark_source_synthetic_prosstt",           "PROSSTT",                  "circle",  "benchmark",      lst(),
  "benchmark_source",       "benchmark_source_synthetic_splatter",          "Splatter",                 "circle",  "benchmark",      lst(),
  "benchmark_trajtype",     "benchmark_tt_cycle",                           "Cycle",                    "circle",  "benchmark",      lst(),
  "benchmark_trajtype",     "benchmark_tt_linear",                          "Linear",                   "circle",  "benchmark",      lst(),
  "benchmark_trajtype",     "benchmark_tt_bifurcation",                     "Bifurcation",              "circle",  "benchmark",      lst(),
  "benchmark_trajtype",     "benchmark_tt_convergence",                     "Convergence",              "circle",  "benchmark",      lst(),
  "benchmark_trajtype",     "benchmark_tt_multifurcation",                  "Multifurcation",           "circle",  "benchmark",      lst(),
  "benchmark_trajtype",     "benchmark_tt_tree",                            "Tree",                     "circle",  "benchmark",      lst(),
  "benchmark_trajtype",     "benchmark_tt_acyclic_graph",                   "Acyclic",                  "circle",  "benchmark",      lst(),
  "benchmark_trajtype",     "benchmark_tt_graph",                           "Connected",                "circle",  "benchmark",      lst(),
  "benchmark_trajtype",     "benchmark_tt_disconnected_graph",              "Disconnected",             "circle",  "benchmark",      lst(),
  "benchmark_execution",    "benchmark_overall_pct_errored_str",            "% Errored",                "text",    NA,               lst(hjust = 1),
  "benchmark_execution",    "benchmark_overall_error_reasons",              "Reason",                   "pie",     "error_reasons",  lst(),
  "scaling_predtime",       "scaling_pred_timescore_cells1m_features100",   "1m cells x 100 features",  "rect",    "scaling",        lst(),
  "scaling_predtime",       "scaling_pred_timescore_cells1m_features100",   "",                         "text",    "white6black4",   lst(label = "scaling_pred_timestr_cells1m_features100", overlay = TRUE, size = 3),
  "scaling_predtime",       "scaling_pred_timescore_cells100k_features1k",  "100k x 1k",                "rect",    "scaling",        lst(),
  "scaling_predtime",       "scaling_pred_timescore_cells100k_features1k",  "",                         "text",    "white6black4",   lst(label = "scaling_pred_timestr_cells100k_features1k", overlay = TRUE, size = 3),
  "scaling_predtime",       "scaling_pred_timescore_cells10k_features10k",  "10k x 10k",                "rect",    "scaling",        lst(),
  "scaling_predtime",       "scaling_pred_timescore_cells10k_features10k",  "",                         "text",    "white6black4",   lst(label = "scaling_pred_timestr_cells10k_features10k", overlay = TRUE, size = 3),
  "scaling_predtime",       "scaling_pred_timescore_cells1k_features100k",  "1k x 100k",                "rect",    "scaling",        lst(),
  "scaling_predtime",       "scaling_pred_timescore_cells1k_features100k",  "",                         "text",    "white6black4",   lst(label = "scaling_pred_timestr_cells1k_features100k", overlay = TRUE, size = 3),
  "scaling_predtime",       "scaling_pred_timescore_cells100_features1m",   "100 x 1m",                 "rect",    "scaling",        lst(),
  "scaling_predtime",       "scaling_pred_timescore_cells100_features1m",   "",                         "text",    "white6black4",   lst(label = "scaling_pred_timestr_cells100_features1m", overlay = TRUE, size = 3),
  "stability",              "stability_correlation",                        "Ordering",                 "circle",  "stability",      lst(),
  "stability",              "stability_him",                                "Topology",                 "circle",  "stability",      lst(),
  "stability",              "stability_featureimp_wcor",                    "Features",                 "circle",  "stability",      lst(),
  "stability",              "stability_F1_branches",                        "Clustering",               "circle",  "stability",      lst(),
  "qc_application",         "qc_app_user_friendly",                         "User friendly",            "circle",  "qc",             lst(),
  "qc_application",         "qc_app_developer_friendly",                    "Developer friendly",       "circle",  "qc",             lst(),
  "qc_application",         "qc_app_future_proof",                          "Future proof",             "circle",  "qc",             lst(),
  "qc_category",            "qc_cat_availability",                          "Availability",             "circle",  "qc",             lst(),
  "qc_category",            "qc_cat_behaviour",                             "Behaviour",                "circle",  "qc",             lst(),
  "qc_category",            "qc_cat_code_assurance",                        "Code assurance",           "circle",  "qc",             lst(),
  "qc_category",            "qc_cat_code_quality",                          "Code quality",             "circle",  "qc",             lst(),
  "qc_category",            "qc_cat_documentation",                         "Documentation",            "circle",  "qc",             lst(),
  "qc_category",            "qc_cat_paper",                                 "Paper",                    "circle",  "qc",             lst()
) # tribble_end



column_groups <- tribble( # tribble_start
  ~Experiment,        ~Category,                      ~group,
  "Method",           "",                             "method_characteristic",
  "Method",           "Inferrable trajectory types",  "inferrable_trajtype",
  "Summary",          "",                             "score_overall",
  "Benchmark",        "Metrics",                      "benchmark_metric",
  "Benchmark",        "Sources",                      "benchmark_source",
  "Benchmark",        "Trajectory types",             "benchmark_trajtype",
  "Benchmark",        "Execution",                    "benchmark_execution",
  "Scalability",      "Predicted time",               "scaling_predtime",
  "Stability",        "",                             "stability",
  "Quality control",  "Application",                  "qc_application",
  "Quality control",  "Category",                     "qc_category"
) # tribble_end

