---
title: "Metric conformity"
output: 
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
header-includes:
  - \usepackage{tabularx}
mainfont: DejaVu Sans
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)
options(knitr.duplicate.label = 'allow')

library(tidyverse)
library(dynbenchmark)

experiment("02-metric_characterisation/01-metric_conformity")
```

```{r}
assessments <- read_rds(derived_file("assessments.rds"))
rules <- read_rds(derived_file("rules.rds"))
```

## Summary

```{r}
assessments %>%
  left_join(rules %>% select(id, name), by = c("rule_id" = "id")) %>%
  unnest(conformity) %>%
  mutate(
    metric_id = label_metrics(metric_id, label_type = "latex") %>% paste0("$", ., "$") %>% forcats::fct_inorder(),
    conforms = kableExtra::cell_spec(
      ifelse(conforms, "\U2714", "\U2716"),
      background = ifelse(conforms, "#2ECC40", "#FF4136"),
      format = "latex"
    ),
    rule_id = forcats::fct_inorder(rule_id)
  ) %>%
  spread(metric_id, conforms) %>%
  select(-rule_id) %>% 
  knitr::kable(format = "latex", escape = FALSE, booktabs = TRUE) %>%
  kableExtra::kable_styling(full_width = FALSE) %>% 
  kableExtra::column_spec(1, width="15em") %>% 
  kableExtra::column_spec(2:20, width = "3em") %>% 
  kableExtra::row_spec(0, angle = 30) %>% 
  gsub("\\\\addlinespace", "", .)
```

\pagebreak

```{r results='asis'}
# assessment <- dynutils::extract_row_to_list(assessments, 1)

walkdf(assessments[, ], function(assessment) {
  cat(knitr::knit_child("assessment.Rmd", quiet=TRUE, envir = environment()))
})
```
